import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Button } from '@eoms/ui'
import type { NextPage } from 'next'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/admin" className={styles.card}>
            <div className={styles.card}>
              <Button postIcon='&rarr;'>
                <h2>Admin</h2>
              </Button>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </Link>

          <Link href="/cli" className={styles.card}>
            <div className={styles.card}>
              <Button postIcon='&rarr;'>
                <h2>Cli</h2>
              </Button>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </div>
          </Link>

          <Link href="/ui" className={styles.card}>
            <div className={styles.card}>
              <Button prevIcon='&rarr;'>
                <h2>UI</h2>
              </Button>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
