name: Deploy Docs to Github Page

env:
  GITHUB_TOKEN: ${{ secrets.SELF_TOKEN }}

# Only trigger, when the Release workflow succeeded
on:
  workflow_run:
    workflows: ['Release']
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Restore cache
        run: pnpm clean:cache

      - name: Build Packages
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
          generator_config_file: ./apps/docs/next.config.js
          token: $GITHUB_TOKEN
      - name: Static HTML export with Next.js
        run: cd ./apps/docs && next export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./apps/docs/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: $GITHUB_TOKEN
