name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Print current workflow info
        run: echo "${{ github.head_ref || github.ref_name }} ${{ github.triggering_actor || github.actor }} $GIT_AUTHOR_NAME $GIT_AUTHOR_EMAIL"
        env:
          GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }} 

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm build

      - name: Fetch Github User Email
        run: git config --global user.email $(git log -n 1 --pretty=format:%ae)

      - name: Fetch Github User Name
        run: git config --global user.name $(git log -n 1 --pretty=format:%an)

      - name: Generate changelogrc
        run: pnpm changelog:gen

      - name: Publish packages and create releases
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: bump versions'
          title: 'chore: bump versions'
          version: pnpm changeset version
          publish: |
            npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.SELF_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Generate changelog files
        run: pnpm changelog:write

      - name: Commit changelog files
        run: |
          git add . && pnpm format
          git diff --staged --quiet || git commit -am "docs: update changelog on repository and website" && git push origin $GITHUB_BRANCH